export const CHANGE_LOGIN_USERNAME_FIELD = 'CHANGE_LOGIN_USERNAME_FIELD';
export const CHANGE_LOGIN_PASSWORD_FIELD = 'CHANGE_LOGIN_PASSWORD_FIELD';

export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';